/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  sym_tag_name = 4,
  anon_sym_EQ = 5,
  sym_attribute_name = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_attribute_value_token1 = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_attribute_value_token2 = 10,
  sym_html_text = 11,
  anon_sym_ATmodel = 12,
  aux_sym_razor_model_directive_token1 = 13,
  sym_type_name = 14,
  sym_identifier = 15,
  anon_sym_AT = 16,
  anon_sym_DOT = 17,
  sym_source_file = 18,
  sym__node = 19,
  sym_html_element = 20,
  sym_html_start_tag = 21,
  sym_html_end_tag = 22,
  sym_attribute = 23,
  sym_attribute_value = 24,
  sym_razor_model_directive = 25,
  sym_razor_expression = 26,
  sym_member_access = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_html_start_tag_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_value_token2] = "attribute_value_token2",
  [sym_html_text] = "html_text",
  [anon_sym_ATmodel] = "@model",
  [aux_sym_razor_model_directive_token1] = "razor_model_directive_token1",
  [sym_type_name] = "type_name",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_html_element] = "html_element",
  [sym_html_start_tag] = "html_start_tag",
  [sym_html_end_tag] = "html_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_razor_model_directive] = "razor_model_directive",
  [sym_razor_expression] = "razor_expression",
  [sym_member_access] = "member_access",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_html_start_tag_repeat1] = "html_start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_value_token2] = aux_sym_attribute_value_token2,
  [sym_html_text] = sym_html_text,
  [anon_sym_ATmodel] = anon_sym_ATmodel,
  [aux_sym_razor_model_directive_token1] = aux_sym_razor_model_directive_token1,
  [sym_type_name] = sym_type_name,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_html_element] = sym_html_element,
  [sym_html_start_tag] = sym_html_start_tag,
  [sym_html_end_tag] = sym_html_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_razor_model_directive] = sym_razor_model_directive,
  [sym_razor_expression] = sym_razor_expression,
  [sym_member_access] = sym_member_access,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_html_start_tag_repeat1] = aux_sym_html_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_html_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATmodel] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_razor_model_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_html_element] = {
    .visible = true,
    .named = true,
  },
  [sym_html_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_razor_model_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_razor_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\'') ADVANCE(20);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '>') ADVANCE(12);
      if (lookahead == '@') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '>') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(2);
      END_STATE();
    case 6:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 8:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '@') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_html_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_html_text);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_ATmodel);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_razor_model_directive_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'm') ADVANCE(5);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_ATmodel] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym__node] = STATE(5),
    [sym_html_element] = STATE(5),
    [sym_html_start_tag] = STATE(3),
    [sym_razor_model_directive] = STATE(5),
    [sym_razor_expression] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_html_text] = ACTIONS(7),
    [anon_sym_ATmodel] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym_html_text,
    STATE(3), 1,
      sym_html_start_tag,
    STATE(10), 1,
      sym_html_end_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [29] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym_html_text,
    STATE(3), 1,
      sym_html_start_tag,
    STATE(8), 1,
      sym_html_end_tag,
    STATE(2), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [58] = 8,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(24), 1,
      anon_sym_LT_SLASH,
    ACTIONS(26), 1,
      sym_html_text,
    ACTIONS(29), 1,
      anon_sym_ATmodel,
    ACTIONS(32), 1,
      anon_sym_AT,
    STATE(3), 1,
      sym_html_start_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [87] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      sym_html_text,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_html_start_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [113] = 3,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(39), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [127] = 2,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(45), 5,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
      anon_sym_DOT,
  [139] = 2,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(49), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [150] = 2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(53), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [161] = 2,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(57), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [172] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(61), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [183] = 2,
    ACTIONS(65), 1,
      sym_html_text,
    ACTIONS(63), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [193] = 2,
    ACTIONS(69), 1,
      sym_html_text,
    ACTIONS(67), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [203] = 3,
    ACTIONS(71), 1,
      anon_sym_GT,
    ACTIONS(73), 1,
      sym_attribute_name,
    STATE(16), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [214] = 3,
    ACTIONS(75), 1,
      anon_sym_GT,
    ACTIONS(77), 1,
      sym_attribute_name,
    STATE(15), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [225] = 3,
    ACTIONS(73), 1,
      sym_attribute_name,
    ACTIONS(80), 1,
      anon_sym_GT,
    STATE(15), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [236] = 3,
    ACTIONS(82), 1,
      anon_sym_DQUOTE,
    ACTIONS(84), 1,
      anon_sym_SQUOTE,
    STATE(19), 1,
      sym_attribute_value,
  [246] = 2,
    ACTIONS(86), 1,
      sym_identifier,
    STATE(6), 1,
      sym_member_access,
  [253] = 1,
    ACTIONS(88), 2,
      anon_sym_GT,
      sym_attribute_name,
  [258] = 1,
    ACTIONS(90), 2,
      anon_sym_GT,
      sym_attribute_name,
  [263] = 1,
    ACTIONS(92), 1,
      aux_sym_attribute_value_token2,
  [267] = 1,
    ACTIONS(94), 1,
      sym_type_name,
  [271] = 1,
    ACTIONS(96), 1,
      aux_sym_razor_model_directive_token1,
  [275] = 1,
    ACTIONS(98), 1,
      anon_sym_EQ,
  [279] = 1,
    ACTIONS(100), 1,
      sym_tag_name,
  [283] = 1,
    ACTIONS(102), 1,
      sym_tag_name,
  [287] = 1,
    ACTIONS(104), 1,
      aux_sym_attribute_value_token1,
  [291] = 1,
    ACTIONS(106), 1,
      sym_identifier,
  [295] = 1,
    ACTIONS(108), 1,
      anon_sym_GT,
  [299] = 1,
    ACTIONS(110), 1,
      anon_sym_DQUOTE,
  [303] = 1,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
  [307] = 1,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 113,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 139,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 161,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 193,
  [SMALL_STATE(14)] = 203,
  [SMALL_STATE(15)] = 214,
  [SMALL_STATE(16)] = 225,
  [SMALL_STATE(17)] = 236,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 253,
  [SMALL_STATE(20)] = 258,
  [SMALL_STATE(21)] = 263,
  [SMALL_STATE(22)] = 267,
  [SMALL_STATE(23)] = 271,
  [SMALL_STATE(24)] = 275,
  [SMALL_STATE(25)] = 279,
  [SMALL_STATE(26)] = 283,
  [SMALL_STATE(27)] = 287,
  [SMALL_STATE(28)] = 291,
  [SMALL_STATE(29)] = 295,
  [SMALL_STATE(30)] = 299,
  [SMALL_STATE(31)] = 303,
  [SMALL_STATE(32)] = 307,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_razor_expression, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_razor_expression, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_razor_model_directive, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_razor_model_directive, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_start_tag_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [112] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_razor(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "razor",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
