/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_LT_SLASH = 3,
  sym_tag_name = 4,
  anon_sym_EQ = 5,
  sym_attribute_name = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_attribute_value_token1 = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_attribute_value_token2 = 10,
  sym_html_text = 11,
  anon_sym_ATmodel = 12,
  aux_sym_razor_model_directive_token1 = 13,
  sym_type_name = 14,
  sym_identifier = 15,
  anon_sym_AT = 16,
  anon_sym_DOT = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  sym_source_file = 20,
  sym__node = 21,
  sym_html_element = 22,
  sym_html_start_tag = 23,
  sym_html_end_tag = 24,
  sym_attribute = 25,
  sym_attribute_value = 26,
  sym_razor_model_directive = 27,
  sym_razor_expression = 28,
  sym_member_access = 29,
  sym_parenthesized_expression = 30,
  sym_expression = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_html_start_tag_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_value_token2] = "attribute_value_token2",
  [sym_html_text] = "html_text",
  [anon_sym_ATmodel] = "@model",
  [aux_sym_razor_model_directive_token1] = "razor_model_directive_token1",
  [sym_type_name] = "type_name",
  [sym_identifier] = "identifier",
  [anon_sym_AT] = "@",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_html_element] = "html_element",
  [sym_html_start_tag] = "html_start_tag",
  [sym_html_end_tag] = "html_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_razor_model_directive] = "razor_model_directive",
  [sym_razor_expression] = "razor_expression",
  [sym_member_access] = "member_access",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_html_start_tag_repeat1] = "html_start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_value_token2] = aux_sym_attribute_value_token2,
  [sym_html_text] = sym_html_text,
  [anon_sym_ATmodel] = anon_sym_ATmodel,
  [aux_sym_razor_model_directive_token1] = aux_sym_razor_model_directive_token1,
  [sym_type_name] = sym_type_name,
  [sym_identifier] = sym_identifier,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_html_element] = sym_html_element,
  [sym_html_start_tag] = sym_html_start_tag,
  [sym_html_end_tag] = sym_html_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_razor_model_directive] = sym_razor_model_directive,
  [sym_razor_expression] = sym_razor_expression,
  [sym_member_access] = sym_member_access,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_html_start_tag_repeat1] = aux_sym_html_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_html_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATmodel] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_razor_model_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_html_element] = {
    .visible = true,
    .named = true,
  },
  [sym_html_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_razor_model_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_razor_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 7,
  [25] = 25,
  [26] = 6,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 9,
  [41] = 41,
  [42] = 12,
  [43] = 33,
  [44] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '"', 17,
        '\'', 20,
        '(', 31,
        ')', 32,
        '.', 30,
        '<', 11,
        '=', 15,
        '>', 12,
        '@', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 7:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 8:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '@') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_html_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_html_text);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_ATmodel);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_razor_model_directive_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_type_name);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '<' ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 9},
  [12] = {.lex_state = 9},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 9},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 8},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_ATmodel] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym__node] = STATE(5),
    [sym_html_element] = STATE(5),
    [sym_html_start_tag] = STATE(2),
    [sym_razor_model_directive] = STATE(5),
    [sym_razor_expression] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_html_text] = ACTIONS(7),
    [anon_sym_ATmodel] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym_html_text,
    STATE(2), 1,
      sym_html_start_tag,
    STATE(10), 1,
      sym_html_end_tag,
    STATE(3), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [29] = 8,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym_html_text,
    STATE(2), 1,
      sym_html_start_tag,
    STATE(13), 1,
      sym_html_end_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [58] = 8,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(24), 1,
      anon_sym_LT_SLASH,
    ACTIONS(26), 1,
      sym_html_text,
    ACTIONS(29), 1,
      anon_sym_ATmodel,
    ACTIONS(32), 1,
      anon_sym_AT,
    STATE(2), 1,
      sym_html_start_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [87] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_ATmodel,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      sym_html_text,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_html_start_tag,
    STATE(4), 5,
      sym__node,
      sym_html_element,
      sym_razor_model_directive,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [113] = 3,
    ACTIONS(41), 1,
      anon_sym_DOT,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(39), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [127] = 2,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(45), 5,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
      anon_sym_DOT,
  [139] = 2,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(49), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [150] = 2,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(39), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [161] = 2,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(53), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [172] = 2,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(57), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [183] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(61), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [194] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(65), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [205] = 2,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_html_text,
    ACTIONS(69), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [216] = 5,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_member_access,
    STATE(31), 1,
      sym_expression,
    STATE(40), 1,
      sym_parenthesized_expression,
  [232] = 5,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_member_access,
    STATE(8), 1,
      sym_expression,
    STATE(9), 1,
      sym_parenthesized_expression,
  [248] = 2,
    ACTIONS(81), 1,
      sym_html_text,
    ACTIONS(79), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [258] = 2,
    ACTIONS(85), 1,
      sym_html_text,
    ACTIONS(83), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_ATmodel,
      anon_sym_AT,
  [268] = 5,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym_member_access,
    STATE(40), 1,
      sym_parenthesized_expression,
    STATE(44), 1,
      sym_expression,
  [284] = 3,
    ACTIONS(87), 1,
      anon_sym_GT,
    ACTIONS(89), 1,
      sym_attribute_name,
    STATE(21), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [295] = 3,
    ACTIONS(91), 1,
      anon_sym_GT,
    ACTIONS(93), 1,
      sym_attribute_name,
    STATE(21), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [306] = 3,
    ACTIONS(89), 1,
      sym_attribute_name,
    ACTIONS(96), 1,
      anon_sym_GT,
    STATE(20), 2,
      sym_attribute,
      aux_sym_html_start_tag_repeat1,
  [317] = 3,
    ACTIONS(98), 1,
      anon_sym_DQUOTE,
    ACTIONS(100), 1,
      anon_sym_SQUOTE,
    STATE(25), 1,
      sym_attribute_value,
  [327] = 1,
    ACTIONS(43), 2,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [332] = 1,
    ACTIONS(102), 2,
      anon_sym_GT,
      sym_attribute_name,
  [337] = 2,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
    ACTIONS(104), 1,
      anon_sym_DOT,
  [344] = 1,
    ACTIONS(106), 2,
      anon_sym_GT,
      sym_attribute_name,
  [349] = 1,
    ACTIONS(108), 1,
      sym_tag_name,
  [353] = 1,
    ACTIONS(110), 1,
      anon_sym_GT,
  [357] = 1,
    ACTIONS(112), 1,
      sym_type_name,
  [361] = 1,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
  [365] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [369] = 1,
    ACTIONS(118), 1,
      sym_identifier,
  [373] = 1,
    ACTIONS(120), 1,
      aux_sym_razor_model_directive_token1,
  [377] = 1,
    ACTIONS(122), 1,
      sym_tag_name,
  [381] = 1,
    ACTIONS(124), 1,
      anon_sym_EQ,
  [385] = 1,
    ACTIONS(126), 1,
      aux_sym_attribute_value_token1,
  [389] = 1,
    ACTIONS(128), 1,
      anon_sym_SQUOTE,
  [393] = 1,
    ACTIONS(128), 1,
      anon_sym_DQUOTE,
  [397] = 1,
    ACTIONS(37), 1,
      anon_sym_RPAREN,
  [401] = 1,
    ACTIONS(130), 1,
      aux_sym_attribute_value_token2,
  [405] = 1,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
  [409] = 1,
    ACTIONS(132), 1,
      sym_identifier,
  [413] = 1,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 113,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 139,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 161,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 194,
  [SMALL_STATE(14)] = 205,
  [SMALL_STATE(15)] = 216,
  [SMALL_STATE(16)] = 232,
  [SMALL_STATE(17)] = 248,
  [SMALL_STATE(18)] = 258,
  [SMALL_STATE(19)] = 268,
  [SMALL_STATE(20)] = 284,
  [SMALL_STATE(21)] = 295,
  [SMALL_STATE(22)] = 306,
  [SMALL_STATE(23)] = 317,
  [SMALL_STATE(24)] = 327,
  [SMALL_STATE(25)] = 332,
  [SMALL_STATE(26)] = 337,
  [SMALL_STATE(27)] = 344,
  [SMALL_STATE(28)] = 349,
  [SMALL_STATE(29)] = 353,
  [SMALL_STATE(30)] = 357,
  [SMALL_STATE(31)] = 361,
  [SMALL_STATE(32)] = 365,
  [SMALL_STATE(33)] = 369,
  [SMALL_STATE(34)] = 373,
  [SMALL_STATE(35)] = 377,
  [SMALL_STATE(36)] = 381,
  [SMALL_STATE(37)] = 385,
  [SMALL_STATE(38)] = 389,
  [SMALL_STATE(39)] = 393,
  [SMALL_STATE(40)] = 397,
  [SMALL_STATE(41)] = 401,
  [SMALL_STATE(42)] = 405,
  [SMALL_STATE(43)] = 409,
  [SMALL_STATE(44)] = 413,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_razor_expression, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_razor_expression, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_razor_model_directive, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_razor_model_directive, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_element, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_element, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_end_tag, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_start_tag, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_start_tag_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_razor(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "razor",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
